### ISSUE TITLE
Percentage display

### ISSUE THREAD

**Issue by talkleasy** [jatu-studiobox/node-red-contrib-ui-widget-thermometer#1]
Is it possible not to display percentages? This does not have a meaning when displaying temperatures. It is the temperature that is important, not the range. Great ui otherwise. Thanks.

**Comment by mishakim** [comment]
I agree, the percentage is not meaningful. Would would be nice, instead, is to show a high and low pointer, like today's forecast for weather, or set points for HVAC.

**Comment by johnwalicki** [comment]
I agree, the percentage is not meaningful in the context of a temperature range.

**Comment by jatu-studiobox** [comment]
Hi, 

Sorry for very late reply and fix.

Now, this issue is fixed to new feature at version 0.6.5 or lastest.

And thank you very much for your issue. :)

**Comment by talkleasy** [comment]
Thanks for the fix. Much better now!
