### ISSUE TITLE
Possibility to change font size

### ISSUE THREAD

**Issue by btuerk89** [jatu-studiobox/node-red-contrib-ui-widget-thermometer#10]
Hi,

it would be very nice to implement the possibility to change the font size of the actual temperature to use the free space. Actually it is too small for use in smarthome dashboard on a 10" tab.
![image](https://github.com/jatu-studiobox/node-red-contrib-ui-widget-thermometer/assets/124655843/2d91a921-c94a-4b51-91f0-a6e8469862dc)

Thank you in advance.

**Comment by jatu-studiobox** [comment]
Sorry for late reply.

Thank you for your comment. Could you share about your 10" tab screen? I will check it before improvement. :-)

**Comment by btuerk89** [comment]
Hi, 

I think it makes no sense to share some picture or screenshot from my tablet. 

But maybe this could help: 
The screenshot above is on my tablet exact 5.7 centimeter wide. Maybe you can zoom it or copy it to e.g. MS Word to that size. Then step back about 1.5 to 2 meters from your screen and try to read the text. --> It is very hard. ;)

In the meanwhile I played a bit with the size (ui_widget_thermometer.js in line 145) and I think 3 is OK as "large text option". With larger texts I figured out that on 100% of the scale the text is cut off at the top. Maybe you can add some free space on top of the mercury in general.

Sorry for the long text and thank you in advance. :)

BR

**Comment by jatu-studiobox** [comment]
Thank you very much for your advise.

I already have found point that need to be fixed, but I'm not sure what size that should be.

Ok. I will be add one more config "current temp font size" at config node instead.

Thank you very much for your reply :)

**Comment by jatu-studiobox** [comment]
Hi, @btuerk89 :)

I have already add this issue in 0.7.7 or lastest version.

Thank you very much for your issue.
