### ISSUE TITLE
Shows "error" when switching tabs

### ISSUE THREAD

**Issue by 0815fox** [jatu-studiobox/node-red-contrib-ui-widget-thermometer#2]
When switching tabs, the thermometer shows "error" until the next message arrives.
In comparison a label just shows the last received value.

**Comment by jatu-studiobox** [comment]
> When switching tabs, the thermometer shows "error" until the next message arrives. In comparison a label just shows the last received value.

Hi,

Sorry for very late reply. Could you please explain about "switching tabs"?

Thank you for your issue. :)

**Comment by jatu-studiobox** [comment]
Ok, now I found this issue.

**Comment by jatu-studiobox** [comment]
Hi,

Now, this issue is fixed at version 0.7.0 or lastest.

And thank you very much for your issue. :)
