### ISSUE TITLE
Should also support decimal numbers (rounding them)

### ISSUE THREAD

**Issue by 0815fox** [jatu-studiobox/node-red-contrib-ui-widget-thermometer#3]
I'd prefer if the thermometer could just round incoming non-integer numbers instead of regarding this as an error.

**Comment by johnwalicki** [comment]
+1

**Comment by jatu-studiobox** [comment]
Hi, 

Sorry for very late reply and fix.

Now, this issue is fixed to new feature at version 0.6.0 or lastest.

And thank you very much for your issue. :)
